spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        concurrency: 20
        max-concurrency: 40
        prefetch: 200
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 2000
          multiplier: 2.0
          max-interval: 20000

logging:
  level:
    com.example.demo: INFO
    org.web3j: INFO

springdoc:
  swagger-ui:
    tryItOutEnabled: false

ethereum:
  node-url: ${ETH_NODE_URL}
  http-timeout: 10000
  max-retries: 3
  retry-delay: 1000

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
