spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        concurrency: 30
        max-concurrency: 60
        prefetch: 300
        retry:
          enabled: true
          max-attempts: 7
          initial-interval: 3000
          multiplier: 2.0
          max-interval: 30000

server:
  port: ${PORT:8080}

logging:
  level:
    com.example.demo: WARN
    org.web3j: WARN

springdoc:
  swagger-ui:
    tryItOutEnabled: false

ethereum:
  node-url: ${ETH_NODE_URL}
  http-timeout: 15000
  max-retries: 5
  retry-delay: 2000

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
